version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/Scalify/puppet-master-client-go

    steps:
      - checkout

      - run:
          name: run tests
          command: go test -v ./...

      - run:
          name: gometalinter
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
            golangci-lint run

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
